final Map<String, List<String>> wishes = {
  'Friend': [
    "Happy Birthday! You get to celebrate not just one but two amazing occasions this season—enjoy every moment of it!",
    "Wishing you a birthday as magical as the holidays! May your December be filled with love, joy, and all your favorite things.",
    "Sending you warm birthday wishes wrapped up in holiday cheer. May your day be merry, bright, and full of cake!",
    "Happy Birthday to someone who makes the winter months a little brighter! May your day be filled with love and joy.",
    "Your birthday is the perfect reason to pause from the holiday rush and celebrate you! Wishing you a fantastic day.",
    "May your birthday sparkle as much as the holiday lights! Wishing you joy, laughter, and a beautiful year ahead.",
    "Having a birthday during the holidays means double the joy! May your special day be filled with love, laughter, and festive fun.",
    "Here’s to a birthday full of warmth, joy, and all the things that make this season—and you—so wonderful",
    "You’re a true friend, and I’m so lucky to have you. Happy birthday!",
    "Wishing you laughter, love, and endless happiness on your special day.",
    "Happy Birthday! May this year bring you closer to your dreams.",
    "Here’s to celebrating YOU today! Have an amazing birthday.",
    "Wishing you joy that multiplies, happiness that lasts, and memories to cherish. Happy birthday!",
    "Happy Birthday to someone who deserves all the wonderful things in life!",
    "May your birthday be filled with laughter, sunshine, and countless blessings.",
    "Happy Birthday! Here’s to another year of fantastic adventures together.",
    "On your birthday, may every moment be unforgettable, just like our friendship.",
    "Cheers to you on your special day! May you shine as bright as the candles on your cake.",
    "Wishing you a birthday filled with heartfelt moments and unforgettable surprises!",
    "Happy Birthday to the person who brings so much light into my life.",
    "May this year bring new milestones and endless happiness into your life!",
    "You make life so much better—happy birthday to an incredible friend!",
    "Happy Birthday! Here’s to more memories, more laughter, and more good times ahead!",
    "Wishing you an unforgettable day filled with all your favorite things!",
    "To my wonderful friend, may your birthday be as sweet and special as you are!",
    "Happy Birthday! Let’s make this year even more awesome than the last one.",
    "I hope today brings you all the happiness and love you deserve. Happy Birthday!",
    "Life is better with friends like you in it. Happy Birthday!",
    "Here’s to another year of friendship, fun, and unforgettable moments. Cheers!",
    "May your birthday be the start of a fantastic new chapter in your life!",
    "Happy Birthday to the one who knows me best and supports me endlessly. I’m so lucky to have you as a friend.",
    "Wishing you a year full of exciting opportunities and success. Happy Birthday!",
    "Happy Birthday to the one who makes life so much brighter and more fun!",
    "May this birthday be as fabulous and unique as you are!",
    "Your friendship is a true gift, and I’m so grateful to celebrate you today. Happy Birthday!",
    "You’ve always been there for me—now it’s my turn to celebrate YOU. Happy Birthday!",
    "Here’s to you and all the wonderful moments we’ll share this year. Happy Birthday!",
    "Wishing you a birthday as fantastic as our friendship!",
    "Happy Birthday! I hope this day is filled with everything you love the most.",
    "You deserve nothing but the best on your birthday. Have an amazing day!",
    "To my partner in fun and laughter, Happy Birthday!",
    "May your birthday be filled with love, laughter, and cake! Lots and lots of cake!",
    "You’re more than a friend—you’re family to me. Happy Birthday!",
    "Wishing you a year of dreams coming true. Happy Birthday!",
    "Here’s to celebrating your amazing self today and always. Happy Birthday!",
    "Life wouldn’t be the same without you in it. Have the best birthday ever!",
    "Happy Birthday! You deserve all the happiness in the world today and always.",
    "Cheers to you and another year of making incredible memories. Happy Birthday!",
    "May this birthday be the start of the best year yet. Wishing you love and laughter today and always!",
    "You’re not just a friend—you’re a blessing. Happy Birthday!",
    "Wishing you a day that’s as special and amazing as you are. Happy Birthday!",
    "You make everything better just by being you. Happy Birthday!",
    "Here’s to celebrating your incredible self—cheers to another amazing year ahead!",
    "To my dearest friend, happy birthday! Let’s make this day unforgettable.",
    "Wishing you love, laughter, and all the things that make you happiest. Happy Birthday!",
    "Happy Birthday to my ride-or-die, my confidant, my amazing friend!",
    "I’m so grateful for you and our friendship. Have a spectacular birthday!",
    "Here’s to celebrating YOU today—happy birthday, my wonderful friend!",
    "May your birthday be filled with joy, surprises, and everything you wish for!",
    "You deserve a day as bright and beautiful as your smile. Happy Birthday!",
    "Wishing you nothing but love, happiness, and unforgettable memories on your birthday!",
    "Cheers to another fabulous year of being you! Happy Birthday!",
    "Your kindness and warmth light up my life—happy birthday to an extraordinary friend!",
    "Here’s to the most amazing friend ever! Have the best birthday ever!",
    "Wishing you endless laughter, happiness, and fun on your special day. Happy Birthday!",
    "Happy Birthday to my partner-in-crime and my greatest supporter. I’m so lucky to have you!",
    "You’re a gift to everyone who knows you—have the happiest birthday, my friend!",
    "Happy Birthday! Here’s to another year of amazing adventures and unforgettable memories!",
    "Your friendship makes every day brighter. Have a fantastic birthday!",
    "Wishing you all the love and joy in the world on your birthday. You deserve it all!",
    "Cheers to the most wonderful friend anyone could ask for. Happy Birthday!",
    "To my one-of-a-kind friend, happy birthday! May your day be as unique and amazing as you are.",
    "You’re not just a friend—you’re my chosen family. Happy Birthday!",
    "Thank you for being such a wonderful friend. Have a birthday as fantastic as you are!",
    "Wishing you a birthday filled with all the things you love most. You deserve it!",
    "You make life brighter just by being in it. Have a fabulous birthday!",
    "Here’s to celebrating you and all the joy you bring into the world. Happy Birthday!",
    "May your birthday be as fun, fabulous, and unforgettable as you are. Cheers to you!",
    "Happy Birthday! You’re the kind of friend who makes life so much better. Have an amazing day!",
    "Wishing you a birthday filled with laughter, love, and everything you could wish for!",
    "To the most incredible friend, happy birthday! May your day be as special as you are.",
    "You’re a true blessing in my life, and I’m so grateful for you. Happy Birthday!",
    "Cheers to celebrating your special day and the amazing person you are! Happy Birthday!",
    "Wishing you the happiest of birthdays and an unforgettable year ahead!",
    "You make the world a better place just by being in it. Happy Birthday, my friend!",
    "May this birthday bring you all the happiness and success you deserve. Have an incredible day!",
    "Happy Birthday to my forever friend! Let’s celebrate YOU today!",
    "To the one who knows me best and still loves me—happy birthday, my wonderful friend!",
    "Here’s to another year of laughter, love, and friendship. Happy Birthday!",
    "You’re one of a kind, and today is all about celebrating YOU. Happy Birthday!",
    "Wishing you endless happiness, love, and unforgettable moments on your birthday!",
    "Happy Birthday! May your day be filled with all the things that bring you joy.",
    "To my amazing friend, happy birthday! You make life so much better.",
    "You’re more than a friend—you’re family. Have the happiest birthday ever!",
    "Wishing you a birthday that’s as special and incredible as you are!",
    "Happy Birthday to my wonderful friend! Let’s make this year unforgettable!"
  ],
  'Sister': [
    "Love you to the moon and back.",
    "May your day be as amazing as you are.",
    "You deserve all the happiness in the world today and always.",
    "Wishing you a fabulous birthday filled with laughter and love!",
    "Happy birthday to my sister and best friend.",
    "To my beautiful sister, happy birthday! You shine today and every day.",
    "Happy birthday! Thanks for being the best part of my life.",
    "Happy birthday to my rock, my sister, and my first best friend.",
    "To my sister, my hero, my forever friend – happy birthday!",
    "You make the world a better place. Have a fantastic birthday!",
    "Wishing you a magical birthday full of surprises, joy, and as much love as you bring to this world each day.",
    "To my wonderful sister – Let’s make your birthday celebration unforgettable.",
    "Happy birthday, sis! May all your dreams come true this year.",
    "Thank you for always being the best sister – happy birthday!",
    "On your birthday and always – I love you!",
    "Happy birthday to my partner-in-crime and my best friend for life.",
    "To the one who knows me best and loves me anyway – happy birthday, sister!",
    "May your birthday be as special and unique as you are, sis!",
    "Here’s to another year of us being fabulous – happy birthday, sister!",
    "Wishing my sister a birthday as extraordinary as her soul.",
    "You light up my life in ways words can’t describe – happy birthday, sis!",
    "Sisters like you are rare and precious – have an incredible birthday!",
    "You make life sweeter just by being you. Happy birthday, sis!",
    "To the one who’s been my guide, my cheerleader, and my confidant – happy birthday!",
    "Happy birthday to the queen of my heart – my sister!",
    "Cheers to another year of being awesome – happy birthday, sis!",
    "Thank you for being my lifelong partner in fun and mischief – happy birthday!",
    "Your kindness and warmth make the world a better place. Happy birthday!",
    "May your birthday bring you endless joy and unforgettable memories.",
    "To my sister, who deserves the very best – happy birthday!",
    "You’ve been my biggest inspiration – happy birthday, sis!",
    "I couldn’t imagine my life without you – happy birthday, dear sister!",
    "Here’s to a year full of blessings, love, and laughter – happy birthday!",
    "Happy birthday to the most beautiful soul I know – my sister!",
    "You are more than a sister; you’re my greatest treasure. Happy birthday!",
    "May your special day be filled with love, happiness, and everything you’ve ever wished for.",
    "You’ve been my rock through thick and thin – happy birthday, sis!",
    "Thank you for all the love, laughs, and memories – happy birthday!",
    "To my sister, my friend, my forever ally – happy birthday!",
    "Wishing you a birthday that’s as fabulous as you are, sis!",
    "Happy birthday to my other half – my sister!",
    "May all your dreams and desires come true this year. Happy birthday!",
    "Happy birthday to the one who makes life brighter and more beautiful.",
    "You are my anchor, my light, and my joy – happy birthday, sister!",
    "To my amazing sister – your presence makes every day worthwhile. Happy birthday!",
    "Let’s make your birthday a celebration for the ages – happy birthday, sis!",
    "To my sister who never fails to amaze me – happy birthday!",
    "Every moment with you is a treasure – have a wonderful birthday!",
    "To my sister, my biggest cheerleader and my greatest friend – happy birthday!",
    "Wishing you a day that’s as incredible as you are, sis!",
    "You are my sunshine on rainy days – happy birthday, sister!",
    "Your love and support mean everything to me – happy birthday!",
    "To my sister, my confidant, and my hero – happy birthday!",
    "Happy birthday to the one who’s made my life so much richer.",
    "Your smile lights up the world – have a brilliant birthday!",
    "May your year ahead be as incredible as your heart, sister.",
    "Here’s to celebrating you in every way imaginable – happy birthday, sis!",
    "You are a true gift to this world – happy birthday, my dear sister!",
    "To my sister, who fills my life with love and laughter – happy birthday!",
    "You deserve every bit of joy that comes your way – happy birthday!",
    "May your day be filled with the love and happiness you bring to others.",
    "Happy birthday to my first friend and forever sister!",
    "You are the definition of grace and strength – happy birthday!",
    "Wishing you all the love and happiness in the world – happy birthday, sis!",
    "Your kindness and beauty inspire me every day – happy birthday!",
    "To my sister, my best friend, my everything – happy birthday!",
    "Thank you for all the wonderful memories we’ve shared – happy birthday!",
    "Here’s to celebrating the amazing person you are – happy birthday, sis!",
    "You’ve made my life so much brighter – happy birthday, sister!",
    "Wishing you a day as fabulous and radiant as you are.",
    "To the one who’s always been there for me – happy birthday, sister!",
    "You’re not just my sister, you’re my favorite person – happy birthday!",
    "Happy birthday to the one who’s made my life so much better.",
    "You are my greatest blessing – happy birthday, sis!",
    "Your spirit is a beacon of light – have a fantastic birthday!",
    "To my sister, my role model, and my friend – happy birthday!",
    "May your birthday be full of surprises and joy, just like you.",
    "You deserve all the happiness in the universe – happy birthday!",
    "Happy birthday to the one who makes life magical, my sister!",
    "Thank you for all the love and laughs – happy birthday, sis!",
    "May your birthday bring you all the love you give to the world.",
    "To my sister, my partner in crime – happy birthday!",
    "Here’s to another year of adventures together – happy birthday!",
    "Your love and compassion inspire me every day – happy birthday!",
    "Happy birthday to my sister, my confidant, and my best friend.",
    "May your birthday be as amazing as your heart, sister!",
    "You are my forever friend and my biggest blessing – happy birthday!",
    "Happy birthday to the one who’s been my greatest support.",
    "Your love is a treasure – have a wonderful birthday, sis!",
    "To my sister, who’s always been my guide – happy birthday!",
    "You are my hero and my best friend – happy birthday, sister!",
    "Here’s to celebrating you, the most amazing sister ever – happy birthday!",
    "May your year ahead be full of happiness, success, and love.",
    "Thank you for always being there for me – happy birthday, sis!",
    "To my sister, who’s made life so much sweeter – happy birthday!",
    "Happy birthday to the one who fills my life with joy and laughter.",
    "You are my anchor and my joy – happy birthday, sister!"
  ],
  'Brother': [
    "Happy birthday, bro! I love you a whole lot.",
    "I’m proud to have you representing the [Last Name] family out there in the world.",
    "Happy birthday to my built-in best friend.",
    "Wishing you a birthday as special as you are.",
    "Happy birthday to my funny, accomplished, kind brother.",
    "I have a feeling this trip around the sun will be a movie.",
    "HBDTTVBBOAT! (Happy Birthday to the very best brother of all time. Keep up!)",
    "Friends may come and go, but siblings are forever. Happy birthday to the best brother.",
    "[Birthday date] is def my favourite holiday. Happy birthday!!!",
    "My life would suck without you, dude.",
    "The title I’m most proud of is your [sister/brother].",
    "Happy personal new year!",
    "In honour of your birthday, let’s eat, drink, and be merry!",
    "Wishing you a birthday as adventurous as you are!",
    "Happy birthday to my favourite gym buddy.",
    "Let’s make this year one for the record books!",
    "Happy birthday to my first and forever hero.",
    "Cheers to another year of being awesome, brother!",
    "You’ve always been my role model. Happy birthday, big bro!",
    "No one can make me laugh like you do. Have an amazing birthday, bro!",
    "To my younger brother: You may be annoying sometimes, but I wouldn’t trade you for the world. Happy birthday!",
    "To my older brother: Thanks for always having my back. Happy birthday!",
    "Your kindness and courage inspire me every day. Happy birthday, brother!",
    "Here’s to celebrating you today and every day. Happy birthday, bro!",
    "May your birthday be filled with laughter, love, and all your favourite things.",
    "Happy birthday to the best brother anyone could ever ask for.",
    "To the one who’s been my partner-in-crime since day one – happy birthday!",
    "I’m so lucky to have you as my brother. Have a fantastic birthday!",
    "Your strength and determination amaze me. Happy birthday, brother!",
    "To my brother, my protector, and my best friend – happy birthday!",
    "You make life so much better just by being in it. Happy birthday, bro!",
    "Wishing you a birthday as incredible as your sense of humour.",
    "May this year bring you nothing but success and happiness. Happy birthday!",
    "To the best big brother ever – thanks for being my mentor and my friend. Happy birthday!",
    "To the best little brother – you’ve grown up to be an amazing person. Happy birthday!",
    "Your support means the world to me. Have a fantastic birthday, bro!",
    "Thank you for always being there for me, no matter what. Happy birthday!",
    "To the coolest brother ever – happy birthday! Let’s celebrate in style!",
    "Happy birthday to my superhero, my brother.",
    "You’ve always been my biggest supporter. Happy birthday, brother!",
    "May this birthday be the start of the best year of your life yet.",
    "To the one who knows me best and loves me anyway – happy birthday, bro!",
    "I hope your birthday is as epic as you are, brother!",
    "Happy birthday to the guy who’s always been my protector and my guide.",
    "You’re not just my brother; you’re my best friend. Happy birthday!",
    "Thanks for all the amazing memories, bro. Let’s make more this year!",
    "Your wisdom and humour make life so much brighter. Happy birthday, bro!",
    "To my brother, my partner in mischief – happy birthday!",
    "You’re my brother by blood and my friend by choice. Happy birthday!",
    "May your birthday be filled with everything you love most.",
    "Wishing you endless happiness and success this year. Happy birthday!",
    "Here’s to another year of you being awesome. Happy birthday, bro!",
    "To my brother, my confidant, and my lifelong friend – happy birthday!",
    "You’re the best brother anyone could ask for. Happy birthday!",
    "May this year bring you closer to all your dreams. Happy birthday!",
    "To my brother, my first friend, and my greatest supporter – happy birthday!",
    "You deserve all the good things in life. Happy birthday, bro!",
    "Happy birthday to my brother and my rock.",
    "Your strength and love inspire me every day. Happy birthday, brother!",
    "To the guy who’s always been my hero – happy birthday, bro!",
    "You’re not just my brother; you’re my greatest blessing. Happy birthday!",
    "May your birthday be as wonderful as you are, brother.",
    "Wishing you all the love and happiness in the world. Happy birthday, bro!",
    "Happy birthday to my brother and my best friend for life!",
    "Your generosity and kindness make the world a better place. Happy birthday!",
    "To the one who’s always been there for me – happy birthday, bro!",
    "You’re my brother and my biggest inspiration. Happy birthday!",
    "Happy birthday to the one who makes life so much fun, my brother!",
    "Your determination and courage inspire me every day. Happy birthday, brother!",
    "To my brother, who’s always been my greatest ally – happy birthday!",
    "You make life brighter just by being in it. Happy birthday, bro!",
    "To my brother, my mentor, and my friend – happy birthday!",
    "Your loyalty and love mean the world to me. Happy birthday, brother!",
    "To the most amazing brother ever – happy birthday!",
    "Wishing you a birthday full of joy, laughter, and love.",
    "Happy birthday to the guy who’s been my biggest cheerleader and my best friend.",
    "To my brother, who’s always been my guide and my protector – happy birthday!",
    "You’re my brother by birth and my friend by choice. Happy birthday!",
    "Your strength and courage inspire me every day. Happy birthday, brother!",
    "To my brother, my hero, and my greatest supporter – happy birthday!",
    "You’re the best brother anyone could ask for. Happy birthday!",
    "Happy birthday to the one who’s made my life so much better.",
    "You’re not just my brother; you’re my favourite person. Happy birthday!",
    "To my brother, my partner in mischief – happy birthday!",
    "You’re my greatest blessing and my best friend. Happy birthday, bro!",
    "Your love and support mean everything to me. Happy birthday, brother!",
    "Happy birthday to the guy who’s always been my protector and my guide.",
    "Wishing you all the happiness and success in the world. Happy birthday!",
    "To the most amazing brother ever – happy birthday! Let’s celebrate!"
  ],
  'Mom': [
    "No one compares to you. You’re the best mom ever. Happy birthday!",
    "You mean the world to me, mom. Wishing you the best birthday.",
    "Wishing the sweetest woman in the world a happy birthday.",
    "Time to make some wishes, mom. Happy birthday!",
    "I can’t wait to celebrate your special day with you. Happy birthday!",
    "Cheers to another trip around the sun!",
    "You’re the best mother anyone could ever ask for. Happy birthday!",
    "Happy birthday to my favorite person in the whole world.",
    "I’m the luckiest person to have a mom like you. Happy birthday!",
    "You’re one-of-a-kind and I love you so much. Happy birthday, mom!",
    "I love you today, tomorrow, and forever. Happy birthday, mom!",
    "Wishing the most wonderful mom the best birthday ever!",
    "Happy birthday to the person who loves me unconditionally.",
    "Happy birthday to my biggest cheerleader!",
    "Wishing my one and only mother a very happy birthday.",
    "Happy birthday to the most caring and loving mom ever!",
    "To my incredible mom, may your day be as beautiful as you are. Happy birthday!",
    "You’ve always been my guiding light. Happy birthday, mom!",
    "You deserve all the love and happiness in the world. Happy birthday!",
    "To the woman who makes every day brighter – happy birthday, mom!",
    "Thanks for being my first teacher and my lifelong friend. Happy birthday!",
    "You’re not just my mom; you’re my best friend. Happy birthday!",
    "Happy birthday to the strongest and most amazing woman I know.",
    "Thank you for always believing in me. Happy birthday, mom!",
    "To my superhero, my mom – happy birthday!",
    "Wishing you endless happiness and love on your special day.",
    "You make every moment in life so much sweeter. Happy birthday, mom!",
    "I hope your birthday is filled with all your favorite things.",
    "To the queen of our family – happy birthday, mom!",
    "You’ve given me so much love and support. I hope today is all about you. Happy birthday!",
    "Wishing the most amazing mom a birthday full of laughter and joy.",
    "You’ve always been my biggest inspiration. Happy birthday, mom!",
    "To my beautiful mother – may your birthday be as wonderful as you are.",
    "You make our family so special. Happy birthday to the heart of our home!",
    "Happy birthday to the woman who taught me everything I know.",
    "Your love is the greatest gift I could ever ask for. Happy birthday!",
    "You’re more than a mom – you’re my best friend. Happy birthday!",
    "Wishing you a birthday as amazing as your love, mom!",
    "Thanks for all the hugs, laughs, and advice. Happy birthday, mom!",
    "To the woman who always knows how to make me smile – happy birthday!",
    "You’ve made every day of my life better. Happy birthday, mom!",
    "Your wisdom and love have guided me through life. Happy birthday!",
    "To the most selfless and loving mom – happy birthday!",
    "I hope your day is as special as you are to me. Happy birthday!",
    "Thanks for being my mom, my friend, and my biggest supporter. Happy birthday!",
    "Wishing you a day filled with relaxation, love, and joy. Happy birthday, mom!",
    "You deserve all the happiness in the world. Happy birthday, mom!",
    "Happy birthday to the woman who gave me life and so much love.",
    "May this year bring you as much happiness as you bring to others. Happy birthday!",
    "To my extraordinary mom – happy birthday!",
    "Wishing you a birthday full of love and surprises, mom!",
    "You make life so much better just by being in it. Happy birthday, mom!",
    "Your love and care mean the world to me. Happy birthday!",
    "You’ve always been my biggest fan. Happy birthday, mom!",
    "I hope your birthday is filled with as much joy as you’ve given me.",
    "Thank you for all the sacrifices you’ve made for me. Happy birthday, mom!",
    "You’re my role model and my hero. Happy birthday, mom!",
    "To my wonderful mom – happy birthday! You deserve the best day ever!",
    "Your kindness and love inspire me every day. Happy birthday!",
    "Wishing you a birthday filled with all your favorite things, mom!",
    "To the best mom in the world – happy birthday!",
    "Your strength and love amaze me every day. Happy birthday, mom!",
    "Happy birthday to the woman who makes every day brighter.",
    "You’ve always been my rock. Happy birthday, mom!",
    "Thank you for your endless love and support. Happy birthday!",
    "To my mom, my friend, and my greatest supporter – happy birthday!",
    "You’re the heart of our family. Happy birthday, mom!",
    "Wishing you all the happiness in the world on your special day.",
    "You’ve always put your family first. Today, it’s all about you. Happy birthday, mom!",
    "Thanks for all the love and care you’ve given me. Happy birthday!",
    "You’re the best mom anyone could ever ask for. Happy birthday!",
    "To my amazing mom – I hope your day is as special as you are.",
    "Your love and wisdom have shaped me into who I am today. Happy birthday!",
    "Happy birthday to the most beautiful and loving mom ever!",
    "Your laughter is the best medicine. Happy birthday, mom!",
    "Wishing you a day full of love and laughter. Happy birthday!",
    "To my mom, my friend, and my inspiration – happy birthday!",
    "You’ve always been my guiding star. Happy birthday, mom!",
    "Your love is the greatest gift I’ve ever received. Happy birthday!",
    "To the most incredible mom – happy birthday!",
    "Wishing you a year full of happiness and love. Happy birthday, mom!",
    "Thank you for being my rock. Happy birthday, mom!",
    "Your strength and love inspire me every day. Happy birthday!",
    "To the best mom ever – happy birthday! Let’s make it a day to remember!"
  ],
  'Dad': [
    "Here's to the man who taught me everything, and who supported me in every step I took through life, Happy birthday, Dad. I can't thank you enough for being in my life.",
    "Thanks, Dad, for being my role model, my go-to guy, and our family’s rock. You’re a real-life superhero, and you deserve an awesome day.",
    "You are my hero, my best friend, my mentor, you are my biggest source of strength. I hope that your birthday is filled with love. Happy birthday!",
    "You have taught me the meaning of love and strength. I am grateful for all the time I spent with you.",
    "Thank you for always believing in me when no one did and thank you for encouraging me to chase my dreams. You are my rock, Dad.",
    "Thank you for battling the demons that lurked under my bed and in my closet and for making me feel secure and cherished! I love you!",
    "I hope today brings you as much joy and happiness as you bring to everyone who is lucky enough to know you.",
    "No matter how old I get, you’ll always be my forever protector.",
    "I hope you know that I love you with every fiber of my body. Happy birthday to the best dad anyone could ever want.",
    "Thank you for always making me feel safe and loved. Sometimes the simplest things are the most precious and cherished.",
    "You’ve always been my personal superhero. Thank you for all the lessons you’ve taught me over the years. Happy birthday, dad!",
    "Nothing could ever break our special bond. I’m lucky to have such a loving father. Happy birthday!",
    "I can always count on you to lift me when I’m low and encourage me to keep going at my heights. Thank you for being you. Happy birthday, dad.",
    "Happy birthday to the man who taught me the value of hard work and perseverance.",
    "Dad, you’ve always been my biggest supporter. I hope your day is as special as you are to me.",
    "Wishing the coolest dad in the world an amazing birthday full of laughter and love.",
    "You’re the one I look up to every day. Thanks for being my hero. Happy birthday, dad!",
    "To the man who gave me everything I needed and more – happy birthday, dad!",
    "Dad, you’re a true inspiration. May your birthday be filled with all the things you love most.",
    "Happy birthday to the best dad ever! You’ve made my life extraordinary.",
    "Wishing you a birthday full of relaxation and joy. You deserve it, dad!",
    "Happy birthday to the person who’s taught me so much about life, love, and happiness.",
    "Thanks for being the kind of dad who always puts his family first. Happy birthday!",
    "You’ve shown me what it means to be a great person. I’m so lucky to call you my dad. Happy birthday!",
    "Dad, you’ve been my teacher, my coach, and my friend. I hope your birthday is as amazing as you are.",
    "You’re my role model, and I’m grateful for your guidance every single day. Happy birthday!",
    "Wishing you a day filled with happiness, love, and all your favorite things. Happy birthday, dad!",
    "To the man who has given me the best memories of my life – happy birthday!",
    "Dad, you make life so much better just by being you. Have a wonderful birthday!",
    "You’ve always been my biggest fan and my greatest supporter. I hope your birthday is incredible, dad!",
    "Thanks for all the sacrifices you’ve made for our family. You’re the best dad anyone could ask for. Happy birthday!",
    "Happy birthday to the man who always knows how to make me smile and feel loved.",
    "You’ve been my rock and my safe place. Happy birthday, dad. I love you!",
    "To my favorite storyteller and life coach – happy birthday, dad!",
    "Thank you for always being there for me. Happy birthday to the world’s best dad!",
    "Dad, you’ve given me so many reasons to be proud. I hope your birthday is as special as you are.",
    "To the man who’s been my guiding light – happy birthday, dad!",
    "You’re not just my dad; you’re my best friend. Happy birthday!",
    "Happy birthday to the funniest and most loving dad out there.",
    "Thanks for being a constant source of strength and wisdom. Happy birthday, dad!",
    "To my hero and my mentor – happy birthday, dad! I love you!",
    "You’ve taught me everything I know about kindness and courage. Happy birthday, dad!",
    "Wishing you a birthday as wonderful as your heart, dad.",
    "Happy birthday to the man who’s always been there to lift me up.",
    "To my amazing dad – may your day be as incredible as you are.",
    "Dad, you’re the glue that holds our family together. Happy birthday!",
    "You’ve always been my biggest supporter and my greatest cheerleader. Happy birthday, dad!",
    "To the man who’s made my life so much better – happy birthday, dad!",
    "Your love and guidance mean the world to me. Happy birthday, dad!",
    "Wishing my amazing dad a fantastic birthday filled with love and laughter.",
    "You’ve given me the greatest gift of all – your unconditional love. Happy birthday, dad!",
    "To my incredible father – may your birthday be filled with all the things that bring you joy.",
    "Happy birthday to the man who makes our family so special.",
    "Thank you for your wisdom, your kindness, and your unwavering support. Happy birthday, dad!",
    "You’re the best dad a person could ask for. I hope your birthday is as amazing as you are.",
    "Happy birthday to the man who taught me how to dream big and work hard.",
    "To the most generous and loving dad – happy birthday!",
    "You’ve been my anchor through all of life’s storms. Happy birthday, dad!",
    "Wishing you a birthday filled with all your favorite things, dad.",
    "Thanks for all the laughter and the lessons, dad. Happy birthday!",
    "To the man who’s always believed in me – happy birthday, dad!",
    "You’re my hero and my role model. Happy birthday, dad!",
    "Wishing the happiest of birthdays to my incredible dad.",
    "You’ve given me so much to be thankful for. Happy birthday, dad!",
    "To my dad, my friend, and my greatest supporter – happy birthday!",
    "You’re the heart and soul of our family. Happy birthday, dad!",
    "Wishing you a year full of happiness, love, and adventure. Happy birthday!",
    "You’ve made every day of my life brighter. Happy birthday, dad!",
    "To the man who’s given me everything – happy birthday, dad!",
    "Thanks for being my rock and my guide. Happy birthday, dad!",
    "To the most incredible dad – happy birthday! I love you!",
    "You’ve always been my biggest inspiration. Happy birthday, dad!",
    "Wishing you a birthday as awesome as you are. Happy birthday, dad!",
    "Thanks for always being there for me. Happy birthday, dad!",
    "To my favorite storyteller and life coach – happy birthday!",
    "You’ve been my greatest teacher and my biggest fan. Happy birthday, dad!",
    "Wishing my amazing dad a fantastic birthday filled with love and laughter.",
    "Happy birthday to the best dad in the world!",
    "Your love and guidance mean the world to me. Happy birthday, dad!",
    "Thanks for being a constant source of strength and wisdom. Happy birthday, dad!",
    "You’re not just my dad; you’re my best friend. Happy birthday!",
    "To the man who always knows how to make me smile – happy birthday, dad!",
    "Happy birthday to the funniest and most loving dad out there.",
    "To my hero and my mentor – happy birthday, dad! I love you!",
    "Dad, you’re the glue that holds our family together. Happy birthday!"
  ],
  'Husband': [
    "Happy birthday to my wonderful husband! You make every day brighter.",
    "To the love of my life, may your birthday be filled with joy and laughter.",
    "Wishing you a birthday as amazing as you are! I love you more than words can say.",
    "Happy birthday to my partner in crime! Here’s to many more adventures together.",
    "You are my rock and my greatest support. Happy birthday, my love!",
    "I’m so lucky to have you as my husband. Happy birthday to the man of my dreams!",
    "Thank you for filling my life with love, laughter, and happiness. Happy birthday!",
    "To my soulmate, my best friend, and my everything – happy birthday!",
    "You deserve all the love and happiness in the world today and always. Happy birthday, darling.",
    "Every moment with you is worth celebrating. Happy birthday, sweetheart!",
    "Wishing the most loving and caring husband a fantastic birthday.",
    "To the man who holds my heart, happy birthday! I love you forever and always.",
    "You make life so much sweeter just by being in it. Happy birthday, my love!",
    "Happy birthday to my favorite person in the entire universe.",
    "To my incredible husband, may your birthday be as amazing as you make my life every day.",
    "You’re my everything, and I’m so grateful for you. Happy birthday, my dear!",
    "To the man who completes me – happy birthday, my love.",
    "Your smile lights up my world. Happy birthday to the most wonderful husband!",
    "Thank you for being my partner in life and love. Happy birthday to the best husband ever!",
    "Happy birthday to the man who makes my heart skip a beat every single day.",
    "To my husband, my hero, and my best friend – happy birthday!",
    "Life with you is a beautiful adventure. Happy birthday, my love!",
    "You make every day feel like a celebration. Happy birthday, darling!",
    "To my perfect match, happy birthday! I love you more every single day.",
    "Wishing my amazing husband a birthday filled with love and joy.",
    "You’re not just my husband; you’re my everything. Happy birthday, sweetheart!",
    "Thank you for being the love of my life. Happy birthday, my darling.",
    "To my one and only, happy birthday! I’m so lucky to call you mine.",
    "You’re my happily ever after. Happy birthday, my love!",
    "To my husband, my forever partner – may your birthday be as incredible as you are.",
    "You’re the reason my life is so full of love and laughter. Happy birthday, my amazing husband!",
    "Happy birthday to the man who makes my dreams come true.",
    "To my husband and my heart, happy birthday! You mean everything to me.",
    "Wishing you a birthday as wonderful as the love you’ve brought into my life.",
    "To my partner, my love, and my best friend – happy birthday!",
    "You make my world brighter just by being in it. Happy birthday, my dearest.",
    "To the man who makes me smile every day – happy birthday, darling!",
    "You’re my love story, and I’m so lucky to have you. Happy birthday, sweetheart!",
    "Thank you for making every day feel like a fairytale. Happy birthday, my love!",
    "To my husband, my favorite person – happy birthday!",
    "You’re the best thing that’s ever happened to me. Happy birthday, my darling.",
    "Wishing you a birthday full of love, laughter, and all your favorite things.",
    "To my wonderful husband, may your day be as special as you make my life every day.",
    "Happy birthday to the man who makes my heart sing!",
    "To the love of my life, happy birthday! You’re my everything.",
    "You make every moment magical. Happy birthday, my amazing husband!",
    "To my best friend, my love, and my forever partner – happy birthday!",
    "You’re the reason I believe in true love. Happy birthday, my darling.",
    "Wishing you a birthday filled with all the love and happiness you bring to my life.",
    "To the most incredible husband, happy birthday! I love you endlessly.",
    "You’re my dream come true. Happy birthday, my amazing husband!",
    "To my husband, my hero, my heart – happy birthday!",
    "Life with you is a blessing. Happy birthday to the best husband ever!",
    "Wishing you a birthday as perfect as you are to me.",
    "To my soulmate and my everything – happy birthday, my love!",
    "Happy birthday to the man who makes my life so beautiful.",
    "To the love of my life, happy birthday! You’re my greatest treasure.",
    "Wishing you a day as incredible as you are. Happy birthday, darling!",
    "To my amazing husband, may your birthday be filled with all the love and happiness you deserve.",
    "You’re my happily ever after. Happy birthday, my one and only.",
    "To the man who makes my world complete – happy birthday, my love!",
    "Wishing you a birthday as sweet and special as you are to me.",
    "Happy birthday to my favorite person in the whole wide world.",
    "To my husband, my heart, my everything – happy birthday!",
    "You’re my partner, my best friend, and my forever love. Happy birthday!",
    "Wishing you a birthday full of love, laughter, and endless happiness.",
    "To the most wonderful husband, happy birthday! You’re my everything.",
    "You’re my anchor and my light. Happy birthday to my amazing husband!",
    "To my husband and my hero – happy birthday! I love you so much.",
    "Wishing you a day as special as the love we share. Happy birthday, my love!",
    "To my one and only, happy birthday! You mean the world to me.",
    "Happy birthday to the man who makes my life complete.",
    "To my husband, my love, and my best friend – happy birthday!",
    "You’re my everything, and I’m so lucky to have you. Happy birthday, sweetheart.",
    "Wishing you a birthday as magical as our love. Happy birthday, my darling!",
    "To my amazing husband, happy birthday! You make my world brighter.",
    "You’re the reason I smile every day. Happy birthday, my love!",
    "To my husband and my forever love – happy birthday!",
    "Wishing you a birthday full of love, laughter, and everything you’ve ever dreamed of.",
    "To the most incredible husband, happy birthday! I love you more than words can say.",
    "You’re my everything, and I’m so grateful for you. Happy birthday, my darling.",
    "To my husband, my rock, and my best friend – happy birthday!",
    "Wishing my amazing husband a birthday filled with all the love and happiness you bring to my life.",
    "To the man who makes every day an adventure – happy birthday!",
    "You’re my love, my light, and my forever. Happy birthday, sweetheart!",
    "To my one and only, happy birthday! You’re my greatest blessing.",
    "Wishing you a birthday as wonderful as you are, my love. Happy birthday!",
    "To my husband, my heart, and my hero – happy birthday! I love you more every day."
  ],
  'Wife': [
    "Happy birthday to my beautiful wife! You are my everything.",
    "To the woman who holds my heart, may your birthday be filled with love and happiness.",
    "Wishing you a day as special as you are! I love you endlessly.",
    "Happy birthday to my best friend and soulmate. Here’s to a wonderful year ahead!",
    "You make my life complete. Happy birthday, my love!",
    "You are the most amazing person I know. Happy birthday to my queen!",
    "Happy birthday to the woman who lights up my life. I love you more every day.",
    "To my soulmate, my partner, my everything – happy birthday, my love!",
    "Thank you for being my anchor and my greatest joy. Happy birthday, sweetheart.",
    "Wishing you a birthday as beautiful and radiant as you are.",
    "To my one and only, happy birthday! You’re the love of my life.",
    "You make every day brighter and more beautiful. Happy birthday, my darling.",
    "Here’s to the most wonderful wife anyone could ever ask for. Happy birthday!",
    "Happy birthday to the woman who makes my heart skip a beat. I love you!",
    "You deserve the world and more. Happy birthday, my dearest wife.",
    "To my love, my heart, my wife – happy birthday! May your day be as amazing as you are.",
    "Happy birthday to my partner in everything. I’m so lucky to have you by my side.",
    "You’re the reason I smile every day. Happy birthday, my love!",
    "To my best friend and the love of my life, happy birthday! I’m so grateful for you.",
    "Wishing the happiest of birthdays to the woman who completes me.",
    "Every day with you is a gift, and I’m so lucky to celebrate another year of you. Happy birthday!",
    "You’re my greatest blessing and my greatest love. Happy birthday, my darling wife!",
    "To the most amazing woman in my life, happy birthday! You’re my everything.",
    "Wishing you a birthday as magical as the love we share. Happy birthday, sweetheart!",
    "Happy birthday to my better half. You make life so much more meaningful.",
    "To my incredible wife, happy birthday! You make every moment special.",
    "You’re my dream come true. Happy birthday, my love!",
    "Thank you for being my partner in life and love. Happy birthday, my darling.",
    "To my one and only, happy birthday! You’re my heart and soul.",
    "You make every day feel like a celebration. Happy birthday, my beautiful wife!",
    "To the love of my life, happy birthday! I’m so lucky to have you.",
    "Wishing you all the love and happiness in the world on your special day. Happy birthday!",
    "To the woman who makes my heart sing, happy birthday! You’re my everything.",
    "Happy birthday to my favorite person in the whole wide world. I love you!",
    "You’re my light, my love, and my life. Happy birthday, my darling wife!",
    "To my incredible wife, may your birthday be as amazing as you make my life every day.",
    "You’re my forever and always. Happy birthday, my love!",
    "Wishing you a day filled with love, laughter, and all your favorite things. Happy birthday!",
    "Happy birthday to the woman who makes every moment magical. I love you!",
    "To my soulmate and my heart, happy birthday! You mean everything to me.",
    "You’re the best thing that’s ever happened to me. Happy birthday, my love!",
    "To my wonderful wife, happy birthday! May this year bring you all the happiness you deserve.",
    "Wishing you a birthday as sweet and special as you are, my love.",
    "To my queen, my partner, my love – happy birthday! You’re my everything.",
    "Happy birthday to the woman who makes my dreams come true. I love you!",
    "To my amazing wife, happy birthday! You make every day brighter and better.",
    "You’re my anchor and my light. Happy birthday, my love!",
    "To my beautiful wife, happy birthday! You’re the reason my life is so wonderful.",
    "Wishing you a day as beautiful and perfect as you are. Happy birthday, my darling!",
    "You’re my love story, and I’m so grateful for you. Happy birthday, sweetheart!",
    "To the most amazing wife, happy birthday! You’re my heart and my home.",
    "You’re my happily ever after. Happy birthday, my love!",
    "To my incredible wife, happy birthday! May your day be filled with love and laughter.",
    "Wishing you a birthday as extraordinary as the love we share. Happy birthday!",
    "To my partner, my best friend, and my forever love – happy birthday, my darling!",
    "You make my world brighter and my heart fuller. Happy birthday, my love!",
    "To the woman who makes my life complete, happy birthday! You’re my everything.",
    "Wishing you a birthday filled with all the love and happiness you bring to my life. Happy birthday!",
    "To my wonderful wife, happy birthday! You make every moment unforgettable.",
    "You’re my forever love and my greatest joy. Happy birthday, my darling!",
    "To my amazing wife, may your birthday be as beautiful as you are. I love you!",
    "You’re my partner in life and love. Happy birthday to my one and only.",
    "Wishing you a day as special as the love we share. Happy birthday, my beautiful wife!",
    "To the love of my life, happy birthday! You make my world a better place.",
    "You’re my everything, and I’m so lucky to have you. Happy birthday, my love!",
    "To my soulmate and my heart, happy birthday! You mean the world to me.",
    "Wishing you a birthday as magical as the love we share. Happy birthday, my darling!",
    "Happy birthday to the woman who makes my heart skip a beat. I love you!",
    "To my incredible wife, happy birthday! You’re my everything and more.",
    "You make my life complete. Happy birthday, my love!",
    "To my best friend and my forever partner, happy birthday! You’re my everything.",
    "Wishing you a day filled with love, laughter, and endless happiness. Happy birthday!",
    "To my amazing wife, happy birthday! You’re my heart, my soul, and my everything.",
    "You’re the reason I wake up with a smile every day. Happy birthday, my love!",
    "To my one and only, happy birthday! You’re my greatest blessing.",
    "Wishing you a birthday as special as you are to me. Happy birthday, my darling!",
    "To my wonderful wife, happy birthday! May your day be as amazing as you make my life.",
    "You’re my light, my love, and my forever. Happy birthday, my beautiful wife!",
    "To the love of my life, happy birthday! You’re my everything and more.",
    "Wishing you a birthday filled with love, laughter, and all your favorite things. Happy birthday!",
    "To my soulmate and my partner, happy birthday! You mean the world to me.",
    "You’re my forever and my always. Happy birthday, my love!",
    "To my amazing wife, happy birthday! You’re my heart, my soul, and my everything.",
    "Wishing you a birthday as wonderful and magical as the love we share. Happy birthday!",
    "To my one and only, happy birthday! You make my world a brighter place.",
    "Happy birthday to the woman who makes my dreams come true. I love you!",
    "To my incredible wife, happy birthday! You’re my everything and more.",
    "You’re my light, my love, and my heart. Happy birthday, my darling wife!",
    "To the woman who holds my heart, happy birthday! You mean everything to me.",
    "Wishing you a birthday as extraordinary as the love we share. Happy birthday!",
    "To my beautiful wife, happy birthday! You make every day feel like a dream.",
    "You’re my happily ever after. Happy birthday, my one and only.",
    "To my soulmate and my partner, happy birthday! You’re my everything.",
    "Wishing you a birthday filled with love, laughter, and all your favorite things. Happy birthday!",
    "To my wonderful wife, happy birthday! You’re the reason my life is so beautiful.",
    "You’re my light, my love, and my forever. Happy birthday, my beautiful wife!"
  ],
  'Son': [
    'Happy birthday to my amazing son! You make us proud every day.',
    'Wishing you a year filled with adventure and fun. Enjoy your special day!',
    'To my wonderful son, may your birthday be as awesome as you are!',
    'Happy birthday! Keep reaching for the stars and never stop dreaming.',
    'You are loved more than you know. Have a fantastic birthday!',
    'Another year of growth, wisdom, and incredible memories. Happy birthday, son!',
    'You bring so much joy and light to our lives. Celebrate big today!',
    'Watching you grow has been the greatest adventure of my life. Happy birthday!',
    'May this year bring you endless happiness, success, and wonderful surprises.',
    'Sending you all the love, hugs, and birthday wishes today and always.',
    'Your strength, kindness, and spirit continue to inspire me every single day.',
    'Wishing you a day filled with laughter, love, and unforgettable moments.',
    'You make our world brighter just by being you. Happy birthday!',
    'May your dreams be big and your happiness be even bigger. Happy birthday!',
    'Celebrating you today and always. You are truly one of a kind.',
    'Another year of making memories, chasing dreams, and growing stronger.',
    'You are a blessing beyond measure. Enjoy your special day!',
    'Sending you all the love, support, and birthday cheer you deserve.',
    'May this year be your best one yet, full of incredible opportunities.',
    'Your spirit and determination continue to amaze me. Happy birthday!',
    'Wishing you a day as wonderful and extraordinary as you are.',
    'You are loved more deeply than any words can express. Happy birthday!',
    'May your birthday be filled with all the joy and magic you bring to our lives.',
    'You are not just growing older, but growing more amazing each year.',
    'Celebrating the incredible person you are and the bright future ahead.',
    'Your kindness, courage, and heart make us incredibly proud. Happy birthday!',
    'Wishing you a day of pure happiness, endless smiles, and wonderful surprises.',
    'You continue to be our greatest adventure and our deepest joy.',
    'May this year bring you closer to all your dreams and wildest aspirations.',
    'Sending you a mountain of love, a galaxy of happiness, and a universe of blessings.',
    'You are a light that shines so bright in our lives. Happy birthday!',
    'Another year of watching you grow, learn, and become more incredible.',
    'May your birthday be as spectacular and unique as your personality.',
    'You are our greatest gift, our deepest love, our most precious treasure.',
    'Wishing you a day filled with laughter that echoes through the years.',
    'Your strength and spirit continue to inspire everyone around you.',
    'You bring so much joy, love, and meaning to our world. Happy birthday!',
    'Wishing you boundless happiness, success, and beautiful memories.',
    'You are loved beyond measure, celebrated beyond words. Happy birthday!',
    'May your day be as special, wonderful, and unique as you are.',
    'You are our greatest blessing, our deepest love, our most cherished gift.',
    'Sending you all the love, support, and birthday magic in the world.',
    'May this year bring you closer to your dreams and highest aspirations.',
    'You continue to amaze us with your strength, kindness, and incredible spirit.',
    'Wishing you a birthday as magnificent and extraordinary as you are.',
    'May your day be filled with all the love, laughter, and joy you deserve.',
    'You are not just growing older, but growing more incredible with each passing year.',
    'Celebrating the unique, amazing, and wonderful person you are today.',
    'Sending you an ocean of love, a mountain of happiness, and endless birthday cheer.',
    'May your birthday be the beginning of the most amazing chapter of your life.',
    'Wishing you a day as special and extraordinary as your beautiful heart.',
    'You are our greatest pride, our deepest love, our most precious gift.',
    'May this year bring you closer to your dreams, your passions, and your true self.',
    'Celebrating the amazing spirit that makes you uniquely you. Happy birthday!',
    'Your strength, courage, and kindness continue to inspire us every single day.',
    'Wishing you a birthday filled with magical moments and beautiful memories.',
    'You are loved more deeply, more completely than words can ever express.',
    'May your day be as bright, beautiful, and extraordinary as you are.',
    'Another year of watching you grow, shine, and become your best self.',
    'You are our greatest adventure, our deepest joy, our most cherished blessing.',
    'Sending you all the love, support, and birthday magic the world can offer.',
    'May this year be your most incredible, successful, and joyful yet.',
    'Your spirit continues to light up our world in the most beautiful ways.',
    'Wishing you a birthday as unique, special, and wonderful as you are.',
    'You are not just our son, but our greatest pride, our deepest love.',
    'May your day be filled with endless happiness, boundless love, and pure joy.',
    'Another year of your incredible journey, marked by growth, love, and success.',
    'You bring more love and light to our lives than you could ever know.',
    'Celebrating your spirit, your dreams, and the amazing path ahead of you.',
    'May this year bring you closer to your dreams, your passions, and your true self.',
    'Another year of watching you shine brightly and make the world a better place.',
    'Sending you all the love, support, and birthday magic in the universe.',
    'You continue to amaze us with your strength, kindness, and incredible spirit.'
  ],
  'Daughter': [
    'Happy birthday to my sweet daughter! You light up our lives.',
    'Wishing you a day filled with joy and laughter. You deserve the best!',
    'To my beautiful daughter, may your birthday be filled with love and happiness.',
    'Happy birthday! Keep shining bright and chasing your dreams.',
    'You are a treasure to our family. Enjoy your special day!',
    'Another year of watching you grow, learn, and become an amazing person.',
    'Your beauty, inside and out, continues to inspire us every single day.',
    'You bring so much joy, love, and light to our world. Happy birthday!',
    'Wishing you a day as wonderful and extraordinary as your spirit.',
    'Our love for you is deeper than any ocean, wider than any sky.',
    'Happy birthday to our precious daughter who makes every day brighter!',
    'May this year bring you closer to all your dreams and wildest aspirations.',
    'You are strong, kind, and absolutely amazing. Never forget that!',
    'Sending you all the love, hugs, and birthday wishes in the world.',
    'Your smile lights up our lives in ways words can never express.',
    'Celebrating another year of your incredible journey through life.',
    'You are our greatest pride, our deepest joy, our most cherished gift.',
    'May your birthday be filled with all the magic and wonder you deserve.',
    'Watching you grow has been the most beautiful adventure of our lives.',
    'To our daughter: you are loved more than you could ever imagine.',
    'Happy birthday to the girl who makes our world complete!',
    'Your kindness, courage, and spirit continue to amaze us every day.',
    'Wishing you a day as special and unique as your beautiful personality.',
    'You are a blessing beyond measure. Enjoy your incredible day!',
    'May this year bring you endless happiness, success, and wonderful surprises.',
    'Our love for you grows stronger with each passing year.',
    'Happy birthday to our shining star who brightens up our entire universe!',
    'You are not just growing older, but growing more amazing each year.',
    'Sending you a mountain of love and a galaxy of birthday wishes.',
    'Your strength and determination continue to inspire everyone around you.',
    'May your birthday be the beginning of the most magical year yet.',
    'You are a true blessing, a precious gift we cherish every single day.',
    'Wishing you a day filled with laughter that echoes through the years.',
    'Our hearts are full of love and pride for the incredible person you are.',
    'Happy birthday to the daughter who makes everything in life worthwhile!',
    'May your dreams be big and your happiness be even bigger.',
    'You continue to amaze us with your grace, intelligence, and beautiful heart.',
    'Celebrating the unique and wonderful person you are today.',
    'Wishing you a birthday as extraordinary and special as you are.',
    'You are our greatest adventure, our deepest love, our most precious treasure.',
    'May this year bring you closer to your passions and your true self.',
    'Happy birthday to our daughter who continues to make us proud every single day!',
    'Your spirit is a light that shines so brightly in our lives.',
    'Sending you all the love, support, and magical birthday wishes.',
    'You are loved more deeply than any words could ever express.',
    'May your birthday be filled with all the joy and magic you bring to our world.',
    'Celebrating another year of your incredible growth and amazing potential.',
    'You are a true blessing, a gift we thank the universe for every day.',
    'Wishing you a day as beautiful and remarkable as your own spirit.',
    'Our love for you knows no bounds. Happy birthday, our precious daughter!',
    'May this year be your most incredible, successful, and joyful yet.',
    'You continue to inspire us with your kindness, strength, and beautiful heart.',
    'Happy birthday to the girl who makes our world infinitely more wonderful!',
    'Sending you an ocean of love and a universe of birthday blessings.',
    'Your journey is a beautiful story we are honored to be part of.',
    'May your birthday be as spectacular and unique as your personality.',
    'You are our greatest pride, our deepest joy, our most cherished gift.',
    'Wishing you a day filled with magical moments and beautiful memories.',
    'Your strength and spirit continue to light up our world in amazing ways.',
    'Happy birthday to our daughter who brings endless love and joy to our lives!',
    'May this year open doors to incredible opportunities and beautiful experiences.',
    'You are not just growing older, but growing more incredible with each passing day.',
    'Celebrating the amazing person you are and the bright future ahead.',
    'Our hearts overflow with love, pride, and joy because of you.',
    'Wishing you a birthday as magnificent and extraordinary as you are.',
    'You are a treasure we hold dear, a blessing we cherish completely.',
    'May your day be filled with all the love, laughter, and happiness you deserve.',
    'Happy birthday to our daughter who continues to amaze us in every possible way!',
    'Your kindness, courage, and spirit are a beacon of hope and love.',
    'Sending you all the support, love, and birthday magic in the world.',
    'You bring light and love to our lives in the most beautiful ways.',
    'May this birthday mark the beginning of your most incredible year yet.',
    'Our love for you is a never-ending story of joy and pride.',
    'Wishing you a day as special and wonderful as your beautiful heart.',
    'You are our greatest adventure, our deepest love, our most precious gift.',
    'Happy birthday to the daughter who makes every moment of life extraordinary!',
    'May your dreams be limitless and your happiness be boundless.',
    'You continue to grow, shine, and inspire us in the most amazing ways.',
    'Celebrating your unique spirit and the incredible person you are becoming.',
    'Sending you a galaxy of love and a universe of birthday wishes.',
    'You are loved more completely and deeply than you could ever imagine.',
    'May this year bring you closer to your dreams and highest aspirations.',
    'Happy birthday to our daughter who is the greatest blessing in our lives!',
    'Your beauty, intelligence, and kindness continue to light up our world.',
    'Wishing you a birthday filled with magical moments and beautiful memories.',
    'You are a true miracle, a gift we thank the universe for every single day.',
    'May your day be as bright, beautiful, and extraordinary as you are.',
    'Our hearts are forever grateful for the joy and love you bring.',
    'Happy birthday to the most incredible daughter anyone could ever wish for!'
  ],
};
